# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from vector_endpoint.grpc_gen.vector.v1 import pattern_pb2 as vector_dot_v1_dot_pattern__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vector/v1/pattern_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VectorPatternServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryPattern = channel.unary_stream(
                '/vector.v1.VectorPatternService/QueryPattern',
                request_serializer=vector_dot_v1_dot_pattern__pb2.PatternQueryRequest.SerializeToString,
                response_deserializer=vector_dot_v1_dot_pattern__pb2.PatternQueryEvent.FromString,
                _registered_method=True)
        self.QueryPatternPage = channel.unary_unary(
                '/vector.v1.VectorPatternService/QueryPatternPage',
                request_serializer=vector_dot_v1_dot_pattern__pb2.PatternPageRequest.SerializeToString,
                response_deserializer=vector_dot_v1_dot_pattern__pb2.PatternPageResponse.FromString,
                _registered_method=True)


class VectorPatternServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def QueryPattern(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryPatternPage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorPatternServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryPattern': grpc.unary_stream_rpc_method_handler(
                    servicer.QueryPattern,
                    request_deserializer=vector_dot_v1_dot_pattern__pb2.PatternQueryRequest.FromString,
                    response_serializer=vector_dot_v1_dot_pattern__pb2.PatternQueryEvent.SerializeToString,
            ),
            'QueryPatternPage': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryPatternPage,
                    request_deserializer=vector_dot_v1_dot_pattern__pb2.PatternPageRequest.FromString,
                    response_serializer=vector_dot_v1_dot_pattern__pb2.PatternPageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vector.v1.VectorPatternService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vector.v1.VectorPatternService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorPatternService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueryPattern(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vector.v1.VectorPatternService/QueryPattern',
            vector_dot_v1_dot_pattern__pb2.PatternQueryRequest.SerializeToString,
            vector_dot_v1_dot_pattern__pb2.PatternQueryEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryPatternPage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vector.v1.VectorPatternService/QueryPatternPage',
            vector_dot_v1_dot_pattern__pb2.PatternPageRequest.SerializeToString,
            vector_dot_v1_dot_pattern__pb2.PatternPageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
